import type { RunReport, LocaleReport, PreviewSample } from './model';
import { HOMEPAGE, PRODUCT, VERSION } from '../version';

export interface HtmlOptions {
  theme?: 'auto' | 'light' | 'dark';
  title?: string;
  /** Include the simulated UI section. */
  includePreview?: boolean;
  /** Extra banner text, e.g. dry-run notice. */
  notice?: string;
}

const SEVERITY_LABEL: Record<string, string> = {
  error: 'Error',
  warn: 'Warning',
  info: 'Info',
  ok: 'OK',
};

export function renderHtmlReport(report: RunReport, options: HtmlOptions = {}): string {
  const title = options.title ?? `${PRODUCT} · ${report.command}`;
  const localeCards = report.locales.map((locale) => renderLocaleCard(locale)).join('\n');
  const preview = options.includePreview === false ? '' : renderPreviewSection(report);
  const issues = renderIssues(report);
  const knowledge = renderKnowledge(report);
  const scan = renderScan(report);
  const theme = options.theme ?? 'auto';

  return `<!doctype html>
<html lang="en" data-theme="${theme}">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(title)}</title>
<style>${STYLES}</style>
</head>
<body>
<header class="hero">
  <div class="hero-top">
    <div>
      <p class="eyebrow">${escapeHtml(PRODUCT)} ${escapeHtml(report.version)} · ${escapeHtml(report.command)}</p>
      <h1>${escapeHtml(report.sourceLocale)} → ${report.locales.length} locale(s)</h1>
      <p class="muted">
        ${escapeHtml(report.startedAt)} · ${(report.durationMs / 1000).toFixed(1)}s ·
        engine <code>${escapeHtml(report.engine)}</code> ·
        memory <code>${escapeHtml(report.memory.driver)}</code> (${report.memory.entries} entries)
      </p>
    </div>
    <div class="hero-actions">
      <button id="theme-toggle" type="button" title="Toggle theme">◐</button>
      <button id="pseudo-toggle" type="button" title="Show pseudo-localised text">pseudo</button>
    </div>
  </div>
  ${options.notice ? `<p class="notice">${escapeHtml(options.notice)}</p>` : ''}
  ${report.dryRun ? '<p class="notice">Dry run — nothing was written to disk.</p>' : ''}
  <div class="cards">
    ${card('Keys', String(report.summary.keys))}
    ${card('Translated', String(report.summary.translated))}
    ${card('From memory', String(report.summary.fromMemory))}
    ${card('Errors', String(report.summary.errors), 'error')}
    ${card('Warnings', String(report.summary.warnings), 'warn')}
    ${card('Infos', String(report.summary.infos), 'info')}
  </div>
</header>

<main>
  <section>
    <h2>Locales</h2>
    <div class="grid">${localeCards}</div>
  </section>
  ${preview}
  ${issues}
  ${scan}
  ${knowledge}
  <section>
    <h2>Notes</h2>
    <ul class="notes">
      ${report.notes.map((note) => `<li>${escapeHtml(note)}</li>`).join('\n') || '<li class="muted">No notes.</li>'}
      ${report.summary.written.length > 0 ? `<li>${report.summary.written.length} file(s) written: ${report.summary.written.map((file) => `<code>${escapeHtml(file)}</code>`).join(', ')}</li>` : ''}
    </ul>
  </section>
</main>

<footer>
  <p class="muted">
    Generated by <a href="${HOMEPAGE}">${PRODUCT}</a> ${VERSION} · private by design: this report is a local file,
    translation memory stays in <code>${escapeHtml(report.memory.location)}</code>.
  </p>
</footer>
<script>${SCRIPT}</script>
</body>
</html>`;
}

function card(label: string, value: string, tone = ''): string {
  return `<div class="card ${tone}"><span class="card-value">${escapeHtml(value)}</span><span class="card-label">${escapeHtml(label)}</span></div>`;
}

function renderLocaleCard(locale: LocaleReport): string {
  const percent = Math.round(locale.coverage * 100);
  const errors = locale.issues.filter((issue) => issue.severity === 'error').length;
  const warnings = locale.issues.filter((issue) => issue.severity === 'warn').length;
  return `<article class="locale">
    <header>
      <h3>${escapeHtml(locale.locale)}</h3>
      <span class="pill ${percent === 100 ? 'ok' : 'warn'}">${percent}%</span>
    </header>
    <div class="bar"><span style="width:${percent}%"></span></div>
    <dl>
      <div><dt>keys</dt><dd>${locale.total}</dd></div>
      <div><dt>translated</dt><dd>${locale.translated}</dd></div>
      <div><dt>missing</dt><dd>${locale.missing}</dd></div>
      <div><dt>empty</dt><dd>${locale.empty}</dd></div>
      <div><dt>frozen</dt><dd>${locale.frozen}</dd></div>
      <div><dt>issues</dt><dd><span class="tone-error">${errors}E</span> / <span class="tone-warn">${warnings}W</span></dd></div>
    </dl>
    <p class="muted small">${locale.files.map((file) => `<code>${escapeHtml(file)}</code>`).join(' ') || 'no catalog file'}</p>
  </article>`;
}

function renderPreviewSection(report: RunReport): string {
  const blocks = report.locales
    .map((locale) => {
      const rows = locale.samples.map((sample) => renderSampleRow(locale.locale, sample)).join('\n');
      if (rows.trim().length === 0) return '';
      return `<details open>
        <summary><strong>${escapeHtml(locale.locale)}</strong> · simulated UI</summary>
        <div class="table-wrap">
          <table class="preview-table">
            <thead><tr><th>Key</th><th>Source</th><th>Translation</th><th>Widget</th><th>Length</th><th>Fits?</th></tr></thead>
            <tbody>${rows}</tbody>
          </table>
        </div>
      </details>`;
    })
    .join('\n');
  if (blocks.trim().length === 0) return '';
  return `<section>
    <h2>UI fit &amp; length <span class="muted small">(measurements use ${reportLocalesFont(report)}; overflow is verified in the browser)</span></h2>
    <p class="muted small">Rendered previews use the widget widths from your length rules. The “Fits?” column is confirmed by a real DOM measurement when this page opens.</p>
    ${blocks}
  </section>`;
}

function reportLocalesFont(report: RunReport): string {
  void report;
  return 'the configured font metrics';
}

function renderSampleRow(locale: string, sample: PreviewSample): string {
  const budget = sample.metrics?.budget;
  const limit = budget?.max;
  const used = sample.metrics ? (budget?.unit === 'px' ? sample.px : sample.chars) : 0;
  const percent = limit ? Math.min(140, Math.round((used / limit) * 100)) : 0;
  const issues = sample.issues
    .slice(0, 3)
    .map((issue) => `<li title="${escapeHtml(issue.message)}">${escapeHtml(issue.code)}</li>`)
    .join('');
  return `<tr data-severity="${sample.severity}" data-locale="${escapeHtml(locale)}">
    <td><code>${escapeHtml(sample.key)}</code></td>
    <td class="source">${escapeHtml(sample.source)}</td>
    <td class="target" data-pseudo="${escapeHtml(sample.pseudo)}">${sample.target === null ? '<em class="tone-warn">— missing —</em>' : escapeHtml(sample.target)}</td>
    <td><span class="widget">${escapeHtml(sample.widget)}</span><span class="muted small"> ${sample.containerPx}px</span></td>
    <td class="length">
      <div class="mini-bar"><span style="width:${percent}%" class="${sample.overBudget ? 'over' : ''}"></span></div>
      <span class="muted small">${used}/${limit ?? '–'} ${budget?.unit ?? ''} · ×${sample.ratio}</span>
    </td>
    <td>
      <span class="demo" style="max-width:${sample.containerPx}px">${sample.target === null ? escapeHtml(sample.source) : escapeHtml(sample.target)}</span>
      <span class="overflow-flag" hidden>overflow</span>
      <ul class="issue-list">${issues}</ul>
    </td>
  </tr>`;
}

function renderIssues(report: RunReport): string {
  const issues = report.issues;
  if (issues.length === 0) {
    return `<section><h2>Validation</h2><p class="muted">No issues found. 🎉</p></section>`;
  }
  const byCode = new Map<string, number>();
  for (const issue of issues) byCode.set(issue.code, (byCode.get(issue.code) ?? 0) + 1);
  const summary = [...byCode]
    .sort((a, b) => b[1] - a[1])
    .map(([code, count]) => `<li><code>${escapeHtml(code)}</code><span class="pill">${count}</span></li>`)
    .join('');
  const rows = issues
    .slice(0, 2000)
    .map(
      (issue) => `<tr data-severity="${issue.severity}" data-locale="${escapeHtml(issue.locale)}" data-code="${escapeHtml(issue.code)}">
      <td><span class="sev ${issue.severity}">${SEVERITY_LABEL[issue.severity] ?? issue.severity}</span></td>
      <td><code>${escapeHtml(issue.code)}</code></td>
      <td>${escapeHtml(issue.locale)}</td>
      <td><code>${escapeHtml(issue.key)}</code></td>
      <td>${escapeHtml(issue.message)}${issue.detail ? `<br /><span class="muted small">${escapeHtml(issue.detail)}</span>` : ''}</td>
      <td class="source">${issue.target ? escapeHtml(issue.target) : ''}</td>
    </tr>`,
    )
    .join('\n');
  return `<section>
    <h2>Validation <span class="muted small">${issues.length} issue(s)</span></h2>
    <ul class="chips">${summary}</ul>
    <div class="filters">
      <label>Severity <select id="filter-severity"><option value="">all</option><option>error</option><option>warn</option><option>info</option></select></label>
      <label>Code <select id="filter-code"><option value="">all</option>${[...byCode.keys()].sort().map((code) => `<option>${escapeHtml(code)}</option>`).join('')}</select></label>
      <label>Locale <select id="filter-locale"><option value="">all</option>${report.locales.map((locale) => `<option>${escapeHtml(locale.locale)}</option>`).join('')}</select></label>
    </div>
    <div class="table-wrap">
      <table id="issues-table">
        <thead><tr><th>Severity</th><th>Code</th><th>Locale</th><th>Key</th><th>Message</th><th>Target</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </div>
  </section>`;
}

function renderScan(report: RunReport): string {
  if (!report.scan) return '';
  const scan = report.scan;
  const list = (items: string[], limit = 40): string =>
    items.length === 0
      ? '<p class="muted small">none</p>'
      : `<ul class="keys">${items.slice(0, limit).map((item) => `<li><code>${escapeHtml(item)}</code></li>`).join('')}${items.length > limit ? `<li class="muted">+${items.length - limit} more</li>` : ''}</ul>`;
  const hardcoded = scan.hardcoded
    .slice(0, 60)
    .map(
      (candidate) => `<tr><td><code>${escapeHtml(candidate.file)}:${candidate.line}</code></td><td>${escapeHtml(candidate.text)}</td><td>${candidate.kind}</td><td>${candidate.confidence.toFixed(2)}</td></tr>`,
    )
    .join('\n');
  return `<section>
    <h2>Code scan <span class="muted small">${scan.filesScanned} file(s)</span></h2>
    <div class="columns">
      <div><h3>Missing keys <span class="pill ${scan.undefinedKeys.length > 0 ? 'error' : 'ok'}">${scan.undefinedKeys.length}</span></h3>${list(scan.undefinedKeys)}</div>
      <div><h3>Unused keys <span class="pill">${scan.unusedKeys.length}</span></h3>${list(scan.unusedKeys)}</div>
      <div><h3>Dynamic keys <span class="pill">${scan.dynamicKeys.length}</span></h3>${list(scan.dynamicKeys)}</div>
    </div>
    <h3>Hardcoded UI copy <span class="pill ${scan.hardcoded.length > 0 ? 'warn' : 'ok'}">${scan.hardcoded.length}</span></h3>
    ${
      scan.hardcoded.length === 0
        ? '<p class="muted small">No hardcoded strings detected.</p>'
        : `<div class="table-wrap"><table><thead><tr><th>Where</th><th>Text</th><th>Kind</th><th>Confidence</th></tr></thead><tbody>${hardcoded}</tbody></table></div>`
    }
  </section>`;
}

function renderKnowledge(report: RunReport): string {
  const memory = report.memory;
  const learned = report.learned;
  const engines = memory.byEngine
    .slice(0, 8)
    .map((engine) => `<li><code>${escapeHtml(engine.engine)}</code> <span class="pill">${engine.entries}</span></li>`)
    .join('');
  const learnedList = learned
    ? learned.details
        .slice(0, 40)
        .map(
          (rule) =>
            `<tr><td>${escapeHtml(rule.kind)}</td><td>${escapeHtml(rule.locale ?? '*')}</td><td><code>${escapeHtml(rule.pattern)}</code></td><td>${escapeHtml(rule.value)}</td><td>${rule.confidence.toFixed(2)}</td></tr>`,
        )
        .join('\n')
    : '';
  return `<section>
    <h2>Private knowledge base</h2>
    <div class="cards">
      ${card('Memory entries', String(memory.entries))}
      ${card('Approved', String(memory.approved))}
      ${card('Frozen', String(memory.frozen))}
      ${card('Rules', String(memory.rules))}
      ${card('Suggestions', String(memory.suggestions))}
      ${card('Runs', String(memory.runs))}
    </div>
    <div class="columns">
      <div><h3>By engine</h3><ul class="keys">${engines || '<li class="muted">none</li>'}</ul></div>
      <div><h3>By locale</h3><ul class="keys">${memory.byLocale.slice(0, 12).map((row) => `<li><code>${escapeHtml(row.locale)}</code> <span class="pill">${row.entries}</span> <span class="muted small">${row.approved} approved · ${row.frozen} frozen</span></li>`).join('') || '<li class="muted">none</li>'}</ul></div>
    </div>
    ${
      learned
        ? `<h3>Learned this run <span class="muted small">glossary ${learned.glossary} · corrections ${learned.corrections} · style ${learned.styles}</span></h3>
           <div class="table-wrap"><table><thead><tr><th>Kind</th><th>Locale</th><th>Pattern</th><th>Value</th><th>Confidence</th></tr></thead><tbody>${learnedList || '<tr><td colspan="5" class="muted">nothing new to learn</td></tr>'}</tbody></table></div>`
        : ''
    }
  </section>`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/gu, '&amp;')
    .replace(/</gu, '&lt;')
    .replace(/>/gu, '&gt;')
    .replace(/"/gu, '&quot;')
    .replace(/'/gu, '&#39;');
}

const STYLES = `
:root {
  color-scheme: light dark;
  --bg: #f6f7fb; --panel: #ffffff; --text: #14161a; --muted: #6b7280; --border: #e3e6ee;
  --accent: #4f46e5; --error: #dc2626; --warn: #d97706; --info: #0891b2; --ok: #16a34a;
}
html[data-theme="dark"] { --bg:#0f1115; --panel:#171a21; --text:#e8eaf0; --muted:#9aa3b2; --border:#262b35; --accent:#8b8cf7; }
@media (prefers-color-scheme: dark) {
  html[data-theme="auto"] { --bg:#0f1115; --panel:#171a21; --text:#e8eaf0; --muted:#9aa3b2; --border:#262b35; --accent:#8b8cf7; }
}
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--text); font:15px/1.55 system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue","Noto Sans SC",sans-serif; }
a { color: var(--accent); }
code { font-family: ui-monospace,SFMono-Regular,Menlo,monospace; font-size: .86em; background: color-mix(in srgb, var(--border) 45%, transparent); padding: .1em .35em; border-radius: 4px; }
.hero { padding: 28px clamp(16px,4vw,48px) 8px; }
.hero-top { display:flex; justify-content:space-between; gap:16px; align-items:flex-start; flex-wrap: wrap; }
h1 { margin:.1em 0 .2em; font-size: clamp(20px,3vw,28px); }
h2 { font-size: 19px; margin: 28px 0 10px; }
h3 { font-size: 15px; margin: 16px 0 6px; }
.eyebrow { text-transform: uppercase; letter-spacing: .12em; font-size: 11px; color: var(--muted); margin: 0; }
.muted { color: var(--muted); }
.small { font-size: 12px; }
.cards { display:flex; gap:10px; flex-wrap: wrap; margin: 16px 0 8px; }
.card { background:var(--panel); border:1px solid var(--border); border-radius:12px; padding:10px 14px; min-width:104px; display:flex; flex-direction:column; }
.card-value { font-size:21px; font-weight:600; }
.card-label { font-size:11px; text-transform:uppercase; letter-spacing:.08em; color:var(--muted); }
.card.error .card-value { color: var(--error); } .card.warn .card-value { color: var(--warn); } .card.info .card-value { color: var(--info); }
main { padding: 0 clamp(16px,4vw,48px) 48px; }
.grid { display:grid; grid-template-columns: repeat(auto-fill,minmax(280px,1fr)); gap:14px; }
.locale { background:var(--panel); border:1px solid var(--border); border-radius:14px; padding:14px; }
.locale header { display:flex; justify-content:space-between; align-items:center; }
.locale h3 { margin:0; font-size:16px; }
dl { display:grid; grid-template-columns: repeat(3,1fr); gap:6px; margin:10px 0; }
dt { font-size:11px; color:var(--muted); text-transform:uppercase; letter-spacing:.06em; }
dd { margin:0; font-weight:600; }
.bar, .mini-bar { background: color-mix(in srgb, var(--border) 70%, transparent); border-radius: 99px; height:7px; overflow:hidden; }
.bar span, .mini-bar span { display:block; height:100%; background: var(--accent); }
.mini-bar span.over { background: var(--error); }
.pill { display:inline-block; font-size:11px; padding:1px 8px; border-radius:99px; background: color-mix(in srgb, var(--accent) 18%, transparent); color: var(--text); }
.pill.ok { background: color-mix(in srgb, var(--ok) 22%, transparent); }
.pill.warn { background: color-mix(in srgb, var(--warn) 22%, transparent); }
.pill.error { background: color-mix(in srgb, var(--error) 22%, transparent); }
.tone-error { color: var(--error); } .tone-warn { color: var(--warn); }
.table-wrap { overflow:auto; border:1px solid var(--border); border-radius:12px; background: var(--panel); }
table { border-collapse: collapse; width:100%; font-size:13px; }
th, td { padding:8px 10px; text-align:left; vertical-align:top; border-bottom:1px solid var(--border); }
th { position: sticky; top:0; background: var(--panel); font-size:11px; text-transform:uppercase; letter-spacing:.06em; color: var(--muted); z-index:1; }
tr:last-child td { border-bottom:none; }
.source { color: var(--muted); }
.sev { font-weight:600; font-size:11px; text-transform:uppercase; }
.sev.error { color: var(--error); } .sev.warn { color: var(--warn); } .sev.info { color: var(--info); }
.chips { display:flex; flex-wrap:wrap; gap:6px; list-style:none; padding:0; margin: 8px 0 14px; }
.chips li { display:flex; gap:6px; align-items:center; background: var(--panel); border:1px solid var(--border); border-radius:99px; padding:2px 10px; font-size:12px; }
.filters { display:flex; gap:12px; margin-bottom:10px; font-size:12px; color: var(--muted); flex-wrap: wrap; }
.filters select { background: var(--panel); color: var(--text); border:1px solid var(--border); border-radius:8px; padding:3px 8px; }
.columns { display:grid; grid-template-columns: repeat(auto-fit,minmax(240px,1fr)); gap:14px; }
.keys { list-style:none; padding:0; margin:6px 0; max-height: 220px; overflow:auto; }
.keys li { display:flex; gap:8px; align-items:center; padding:2px 0; border-bottom:1px dashed color-mix(in srgb, var(--border) 80%, transparent); }
.hero-actions button { background: var(--panel); color: var(--text); border:1px solid var(--border); border-radius:10px; padding:6px 12px; cursor:pointer; }
.hero-actions { display:flex; gap:8px; }
.notice { background: color-mix(in srgb, var(--warn) 16%, transparent); border:1px solid color-mix(in srgb, var(--warn) 40%, transparent); padding:8px 12px; border-radius:10px; }
.demo { display:inline-block; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; vertical-align:middle; border:1px dashed var(--border); border-radius:6px; padding:2px 6px; background: color-mix(in srgb, var(--accent) 6%, transparent); }
.demo.overflow { border-color: var(--error); box-shadow: inset 0 0 0 1px var(--error); }
.overflow-flag { color: var(--error); font-size:11px; margin-left:6px; }
.issue-list { list-style:none; padding:0; margin:4px 0 0; font-size:11px; color: var(--muted); }
details { background: var(--panel); border:1px solid var(--border); border-radius:12px; padding:10px 14px; margin:10px 0; }
summary { cursor:pointer; }
.notes { padding-left: 18px; }
footer { padding: 0 clamp(16px,4vw,48px) 40px; }
`;

const SCRIPT = `
(function () {
  var root = document.documentElement;
  var toggle = document.getElementById('theme-toggle');
  if (toggle) {
    toggle.addEventListener('click', function () {
      var current = root.getAttribute('data-theme');
      root.setAttribute('data-theme', current === 'dark' ? 'light' : 'dark');
    });
  }
  // Real DOM overflow measurement: the dashboard validates fit, not just metrics.
  var demoNodes = document.querySelectorAll('.demo');
  demoNodes.forEach(function (node) {
    var limits = node.style.maxWidth;
    if (!limits) return;
    if (node.scrollWidth > node.clientWidth + 1) {
      node.classList.add('overflow');
      var flag = node.parentElement && node.parentElement.querySelector('.overflow-flag');
      if (flag) flag.hidden = false;
    }
  });
  // Filtering
  function applyFilters() {
    var sev = (document.getElementById('filter-severity') || {}).value || '';
    var code = (document.getElementById('filter-code') || {}).value || '';
    var locale = (document.getElementById('filter-locale') || {}).value || '';
    document.querySelectorAll('#issues-table tbody tr').forEach(function (row) {
      var show = (!sev || row.dataset.severity === sev) && (!code || row.dataset.code === code) && (!locale || row.dataset.locale === locale);
      row.style.display = show ? '' : 'none';
    });
  }
  ['filter-severity', 'filter-code', 'filter-locale'].forEach(function (id) {
    var node = document.getElementById(id);
    if (node) node.addEventListener('change', applyFilters);
  });
  var pseudoToggle = document.getElementById('pseudo-toggle');
  if (pseudoToggle) {
    pseudoToggle.addEventListener('click', function () {
      document.querySelectorAll('.target').forEach(function (cell) {
        if (cell.dataset.pseudo) cell.textContent = cell.dataset.pseudo;
      });
    });
  }
})();
`;
